# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=50)),
                ('agency_type', models.CharField(choices=[('CR', 'Credit'), ('CA', 'Cash')], max_length=2)),
                ('agency_minimum_balance', models.FloatField(default=1000000.0)),
                ('agency_current_balance', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='AgentAWBList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airwaybill', models.CharField(max_length=11)),
                ('awb_pieces', models.IntegerField()),
                ('rcvd_pieces', models.IntegerField()),
                ('awb_weight', models.FloatField(default=0.0)),
                ('rcvd_weight', models.FloatField(default=0.0)),
                ('flight_date', models.DateTimeField()),
                ('input_date', models.DateTimeField()),
                ('exit_date', models.DateTimeField()),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NahcoTrack.AgencyDetail')),
            ],
        ),
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banks', models.CharField(choices=[('Access', 'Access Bank'), ('GTBank', 'Guaranty Trust Bank'), ('FBN', 'First Bank Nigeria'), ('Skye', 'Skye Bank'), ('ZBN', 'Zenith Bank Nigeria'), ('UBA', 'United Bank for Africa'), ('Fidelity', 'Fidelity Bank'), ('Stanbic', 'Stanbic IBTC')], default='Access', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DailySales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_date', models.DateTimeField()),
                ('sales_type', models.CharField(choices=[('CR', 'Credit'), ('CA', 'Cash')], max_length=2)),
                ('net_sales', models.FloatField(default=0.0)),
                ('vat', models.FloatField(default=0.0)),
                ('total_stamp', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='EventActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(max_length=3)),
                ('event_actions', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EventTrail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_action_success', models.BooleanField(default=1)),
                ('event_time', models.DateTimeField()),
                ('event_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NahcoTrack.EventActions')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('IMP', 'Import'), ('EXP', 'Export'), ('COU', 'Courier'), ('COA', 'COA')], default='IMP', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.FloatField(default=0.0)),
                ('payment_date', models.DateTimeField()),
                ('payment_mode', models.CharField(choices=[('CA', 'Cash'), ('CQ', 'Cheque'), ('DR', 'Bank Draft'), ('TR', 'Transfer')], max_length=2)),
                ('teller_no', models.CharField(max_length=10)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NahcoTrack.AgencyDetail')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentUtilizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_amount', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('staff_no', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='TellerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teller_date', models.DateTimeField()),
                ('teller_no', models.CharField(max_length=10)),
                ('teller_amount', models.FloatField(default=0.0)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NahcoTrack.AgencyDetail')),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NahcoTrack.Staff')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NahcoTrack.Banks')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NahcoTrack.Location')),
                ('software', models.ForeignKey(default='Galaxy', on_delete=django.db.models.deletion.CASCADE, to='NahcoTrack.Software')),
            ],
        ),
        migrations.AddField(
            model_name='paymentutilizations',
            name='authorized_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NahcoTrack.Staff'),
        ),
        migrations.AddField(
            model_name='paymentutilizations',
            name='awb_on_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NahcoTrack.AgentAWBList'),
        ),
        migrations.AddField(
            model_name='payments',
            name='authorized_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NahcoTrack.Staff'),
        ),
        migrations.AddField(
            model_name='eventtrail',
            name='event_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NahcoTrack.Staff'),
        ),
        migrations.AddField(
            model_name='dailysales',
            name='Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NahcoTrack.Location'),
        ),
        migrations.AddField(
            model_name='agentawblist',
            name='authorized_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NahcoTrack.Staff'),
        ),
    ]
