# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=50)),
                ('agency_type', models.CharField(choices=[('CR', 'Credit'), ('CA', 'Cash')], max_length=2)),
                ('agency_minimum_balance', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('agency_current_balance', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['-agency_name'],
            },
        ),
        migrations.CreateModel(
            name='AgentAWBList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airwaybill', models.CharField(max_length=11)),
                ('awb_pieces', models.IntegerField()),
                ('rcvd_pieces', models.IntegerField()),
                ('awb_weight', models.FloatField(default=0.0)),
                ('rcvd_weight', models.FloatField(default=0.0)),
                ('flight_date', models.DateField()),
                ('input_date', models.DateField()),
                ('exit_date', models.DateField()),
                ('awb_cleared', models.BooleanField(default=False)),
                ('agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NahcoTrack.AgencyDetail')),
            ],
            options={
                'ordering': ['-exit_date'],
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banks', models.CharField(choices=[('Access', 'Access Bank'), ('GTBank', 'Guaranty Trust Bank'), ('FBN', 'First Bank Nigeria'), ('Skye', 'Skye Bank'), ('ZBN', 'Zenith Bank Nigeria'), ('UBA', 'United Bank for Africa'), ('Fidelity', 'Fidelity Bank'), ('Stanbic', 'Stanbic IBTC')], default='Skye', max_length=10)),
            ],
            options={
                'ordering': ['-banks'],
            },
        ),
        migrations.CreateModel(
            name='DailySales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_date', models.DateField()),
                ('sales_type', models.CharField(choices=[('CR', 'Credit'), ('CA', 'Cash')], max_length=2)),
                ('net_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_stamp', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['-sales_date', 'Location'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('IMP', 'Import'), ('EXP', 'Export'), ('COU', 'Courier'), ('COA', 'COA')], default='IMP', max_length=3)),
            ],
            options={
                'ordering': ['-location'],
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_mode', models.CharField(choices=[('CA', 'Cash'), ('CQ', 'Cheque'), ('DR', 'Bank Draft'), ('TR', 'Transfer')], default='Cash', max_length=2)),
                ('teller_no', models.CharField(max_length=11)),
                ('agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NahcoTrack.AgencyDetail')),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NahcoTrack.Bank')),
            ],
            options={
                'ordering': ['bank', 'payment_date', '-teller_no'],
            },
        ),
        migrations.CreateModel(
            name='PaymentUtilizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('utilization_date', models.DateField(null=True)),
                ('awb_on_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NahcoTrack.AgentAWBList')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NahcoTrack.Payments')),
            ],
            options={
                'ordering': ['payment', '-utilization_date'],
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software', models.CharField(max_length=6)),
            ],
            options={
                'ordering': ['-software'],
            },
        ),
        migrations.CreateModel(
            name='TellerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teller_date', models.DateField()),
                ('teller_no', models.CharField(max_length=10)),
                ('teller_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('PO', 'POS'), ('BA', 'Bank'), ('TR', 'Transfer')], default='BA', max_length=2)),
                ('agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NahcoTrack.AgencyDetail')),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NahcoTrack.Bank')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NahcoTrack.Location')),
                ('software', models.ForeignKey(default='Galaxy', null=True, on_delete=django.db.models.deletion.SET_NULL, to='NahcoTrack.Software')),
            ],
            options={
                'ordering': ['software', '-bank', 'teller_no', 'teller_amount'],
            },
        ),
        migrations.AddField(
            model_name='dailysales',
            name='Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NahcoTrack.Location'),
        ),
    ]
