# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NahcoTrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_utilized',
            field=models.BooleanField(default=False),
        ),
    ]
